version: '3.8'
services: 
  post-system:
    image: post-system
    build: .
    ports:
      - "5010:5000"
  post-frontend:
    image: post-frontend
    build: ./frontend
    ports:
      - "3030:3000"
    links:
      - post-system

