version: '3.8'
services: 
  post-system:
    image: post-system
    build: .
    ports:
      - "5010:5010"
  post-frontend:
    image: post-frontend
    build: ./frontend
    ports:
      - "3030:3030"
    links:
      - post-system

